// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXrBo7Y3-nlPZZlPjUp0kg74nAi0lNes',
    appId: '1:751153102438:web:77e94e19c81c581f45f7a7',
    messagingSenderId: '751153102438',
    projectId: 'datingapp-9ce54',
    authDomain: 'datingapp-9ce54.firebaseapp.com',
    storageBucket: 'datingapp-9ce54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPV3j7VDEgmYI0-2-xltV5vDYkS2mHds',
    appId: '1:751153102438:android:614459cb77c7e1ce45f7a7',
    messagingSenderId: '751153102438',
    projectId: 'datingapp-9ce54',
    storageBucket: 'datingapp-9ce54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBqGzEtrU_G5kF2FobCgEY7jwN2NJw9oA',
    appId: '1:751153102438:ios:aa03410121644f1845f7a7',
    messagingSenderId: '751153102438',
    projectId: 'datingapp-9ce54',
    storageBucket: 'datingapp-9ce54.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBqGzEtrU_G5kF2FobCgEY7jwN2NJw9oA',
    appId: '1:751153102438:ios:d9b3223884b3767e45f7a7',
    messagingSenderId: '751153102438',
    projectId: 'datingapp-9ce54',
    storageBucket: 'datingapp-9ce54.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
